### ISSUE TITLE
ARTnet Weighting

### ISSUE THREAD

**Issue by andsv2** [EpiModel/ARTnet#13]
Currently, within the ARTnet workflow, individual level statistics are scaled up to population levels. Alternatively, weighting should happen at the beginning of estimation and carried through the ARTnet workflow.

Note: "weight" parameter in `glm()` only applies to estimation of co-variance matrix under the assumption that model residuals are uncorrelated. Suggest looking at package "survey" for motivating examples on population weighting.

**Comment by andsv2** [comment]
@smjenness: started this issue with the idea that it might be the cause of edge inconsistency. Should we revisit?

**Comment by martinamorris** [comment]
> Note: "weight" parameter in `glm()` only applies to estimation of co-variance matrix under the assumption that model residuals are uncorrelated. Suggest looking at package "survey" for motivating examples on population weighting.

interesting -- i had it on my TODO list to check what this did.  it would be good to have a writeup of how weights are handled in the various R packages we depend on (i.e., don't write ourselves).

for the SHAMP project, we did weight at the beginning of the analysis, so all non-network summary stats reflect our weights.  `ergm.ego` knows how to work with weights, so all the netstats get handled appropriately.

we have been using the `srvyr` package, rather than `survey` these days.   it's designed to work with the tidyverse tools, and makes it easier to add CIs in ggplots (think, histograms).  @netterie has done most of this work to date.

**Comment by smjenness** [comment]
@andsv2 : thanks for relaunching this issue. And let's keep this conversation going with @martinamorris and her team. 

Could you start by outlining here the current issue (e.g., the problem of calculating the expected edges statistic when there is an imbalance between the sample distribution and population distribution of race, and mean degree varies by race).

**Comment by martinamorris** [comment]
This is a good (if brief) summary:
https://stats.stackexchange.com/questions/57107/use-of-weights-in-svyglm-vs-glm
