### ISSUE TITLE
Updates to ASMR implementation

### ISSUE THREAD

**Issue by smjenness** [EpiModel/ARTnet#42]
- [x] Update the default ASMR in build_netstats using 2020 census data
- [x] Create a new function, `update_asmr` that allows user to pass in data frame of race and age specific MR, preloaded from a CSV file, data frame gets passed into function
- [ ] Import census-based age pyramid data for men: proportion of males who are age X, from age 1 to age 100.

**Comment by smjenness** [comment]
@karina-d-wallrafen : adding a new task related to this for you. See third bullet above. Thanks

**Comment by smjenness** [comment]
@karina-d-wallrafen : please note I updated `build_netstats` handling of ASMRs at the upper age limit [here](https://github.com/EpiModel/ARTnet/pull/47/files#diff-3a2f4fbad6b8fd25b93a66fc82250e134b90b6b4ad310e8990be44cbc3027764). Make sure to update from `main` and resolve any conflicts on your branch.

**Comment by karina-d-wallrafen** [comment]
`build_netstats` has been updated [here](https://github.com/EpiModel/ARTnet/commit/32cee25301d4ef38040c81fa73159cb33adeddf4) with 2020 NCHS data on the proportion of men (aged at least 1) who are 1, 2, ..., 100. 

(Since NCHS does not publish population sizes for one-year age groups past age 84, the population sizes for 85- to 100-year-olds were estimated by assuming that each age group was 0.86 times the size of the one before, so that the total 85+ population added up to the expected number).
